<?php
/**
 * @file
 * Main module file for the webform_tabs module.
 */

/**
 * Implements hook_webform_component_info().
 */
function webform_tabs_webform_component_info() {
  $components = array();

  $components['tabs_grp'] = array(
    'label' => t('tabs Container'),
    'description' => t('A container for grouping the tabs of an tabs.'),
    'features' => array(
      'csv' => FALSE,
      'default_value' => FALSE,
      'required' => FALSE,
      'conditional' => FALSE,
      'group' => TRUE,
      'title_inline' => FALSE,
    ),
    'file' => 'components/tabs_container.inc',
  );

  $components['tabs_tab'] = array(
    'label' => t('tabs Tab'),
    'description' => t('A single tab in the tabs.  Must be placed inside of an tabs Container.'),
    'features' => array(
      'csv' => FALSE,
      'default_value' => FALSE,
      'required' => FALSE,
      'conditional' => FALSE,
      'group' => TRUE,
      'title_inline' => FALSE,
    ),
    'file' => 'components/tabs_tab.inc',
  );

  return $components;
}

/**
 * Implements hook_theme().
 */
function webform_tabs_theme() {
  return array(
    'webform_tabs_tab' => array(
      'render element' => 'element',
    ),
    'webform_tabs_tab_template' => array(
      'variables' => array(
        'id' => NULL,
        'title' => NULL,
        'children' => NULL,
        'element' => NULL,
      ),
      'path' => drupal_get_path('module', 'webform_tabs') . '/templates',
      'template' => 'webform-tabs-tab',
    ),
  );
}

/**
 * Helper function for embedding the module js and css files.
 */
function webform_tabs_insert_js_css() {
  static $embedded = FALSE;

  if (!$embedded) {
    drupal_add_library('system', 'ui');
    drupal_add_library('system', 'ui.widget');
    drupal_add_library('system', 'ui.tabs');
    drupal_add_js(drupal_get_path('module', 'webform_tabs') . '/js/webform_tabs.js');

    $embedded = TRUE;
  }
}
